Repository exercism/tcl, pull requests merged in 2025-07, with the labels that each got.

#383 Add a video link to the About page.
  docs/ABOUT.md
Labels: x:rep/small

#385 Update notes-on-unimplemented-exercises.md
  notes-on-unimplemented-exercises.md
Labels: x:rep/tiny

#387 ci uses ubuntu-24.04
  .github/workflows/ci.yml
  .github/workflows/pr.yml
Labels: x:rep/small

#389 Add split-second-stopwatch exercise
  config.json
  exercises/practice/split-second-stopwatch/.docs/instructions.md
  exercises/practice/split-second-stopwatch/.docs/introduction.md
  exercises/practice/split-second-stopwatch/.meta/config.json
  exercises/practice/split-second-stopwatch/.meta/example.tcl
  exercises/practice/split-second-stopwatch/.meta/tests.toml
  exercises/practice/split-second-stopwatch/split-second-stopwatch.tcl
  exercises/practice/split-second-stopwatch/split-second-stopwatch.test
  exercises/practice/split-second-stopwatch/testHelpers.tcl
  notes-on-unimplemented-exercises.md
Labels: x:rep/large

#390 Un-forego micro-blog, and run CI in the tcl-test-runner image
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  bin/ci
  bin/pr
  bin/verify-in-test-runner.tcl
  config.json
  exercises/practice/micro-blog/.docs/instructions.append.md
  exercises/practice/micro-blog/.docs/instructions.md
  exercises/practice/micro-blog/.meta/config.json
  exercises/practice/micro-blog/.meta/example.tcl
  exercises/practice/micro-blog/.meta/tests.toml
  exercises/practice/micro-blog/micro-blog.tcl
  exercises/practice/micro-blog/micro-blog.test
  exercises/practice/micro-blog/testHelpers.tcl
  notes-on-unimplemented-exercises.md
Labels: x:rep/large

#393 improve verify script output again
  bin/verify-in-test-runner.tcl
Labels: x:rep/tiny
